package com.commissionhub.commission_hub.enums;

public enum NotificationType {
    TASK_COMPLETED, TASK_APPROVED, TASK_REJECTED, TASK_OVERDUE,
    PAYMENT_SCHEDULED, PAYMENT_COMPLETED,
    ADJUSTMENT_REQUESTED, ADJUSTMENT_APPROVED, HANDOVER_REQUIRED
}